name: Auto Merge Dependabot PRs

on:
  pull_request_target:
    paths-ignore:
      - '**.php'
      - '**.yml'
      - '**.yaml'
      - '**.md'
      - '**.svg'
      - '**.xml'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_AUTO_MERGE }}
